from . import covid
from . import dates
from . import emails
from . import jokes
from . import file
from . import read_text
from . import screenshot
from . import search_google
from . import weathers
from . import window_features
from . import wishing
from . import time_table
from . import whatsapp