# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'work.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtWidgets import QFrame


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(321, 101)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QSize(321,101))
        Form.setMaximumSize(QSize(321,101))
        self.listener = QtWidgets.QLabel(Form)
        self.listener.setGeometry(QtCore.QRect(0, 0, 141, 101))
        self.listener.setText("")
        self.listener.setPixmap(QtGui.QPixmap(r"gui/images/sound.gif"))
        self.listener.setScaledContents(True)
        self.listener.setObjectName("listener")
        self.result = QtWidgets.QLabel(Form)
        self.result.setGeometry(QtCore.QRect(140, -1, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setItalic(False)
        self.result.setFont(font)
        self.result.setAutoFillBackground(True)
        self.result.setText("")
        self.result.setFrameShape(QFrame.WinPanel)
        self.result.setTextFormat(QtCore.Qt.PlainText)
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(140, 30, 181, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(r"gui/images/initial.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pause = QtWidgets.QPushButton(Form)
        self.pause.setEnabled(True)
        self.pause.setGeometry(QtCore.QRect(180, 50, 31, 31))
        self.pause.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"gui/images/Button-Play-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pause.setIcon(icon)
        self.pause.setIconSize(QtCore.QSize(35, 35))
        self.pause.setCheckable(False)
        self.pause.setAutoDefault(False)
        self.pause.setDefault(False)
        self.pause.setFlat(True)
        self.pause.setObjectName("pause")
        self.setting = QtWidgets.QPushButton(Form)
        self.setting.setGeometry(QtCore.QRect(250, 50, 31, 31))
        self.setting.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(r"gui/images/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.setting.setIcon(icon1)
        self.setting.setIconSize(QtCore.QSize(30, 30))
        self.setting.setFlat(True)
        self.setting.setObjectName("setting")
        self.play = QtWidgets.QPushButton(Form)
        self.play.setEnabled(True)
        self.play.setGeometry(QtCore.QRect(180, 50, 31, 31))
        self.play.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(r"gui/images/Pause-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.play.setIcon(icon2)
        self.play.setIconSize(QtCore.QSize(30, 30))
        self.play.setAutoDefault(False)
        self.play.setDefault(False)
        self.play.setFlat(True)
        self.play.setObjectName("play")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
