# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 190)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(400, 190))
        Form.setMaximumSize(QtCore.QSize(400, 190))
        self.id = QtWidgets.QLabel(Form)
        self.id.setGeometry(QtCore.QRect(80, 50, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.id.setFont(font)
        self.id.setAlignment(QtCore.Qt.AlignCenter)
        self.id.setObjectName("id")
        self.id_name = QtWidgets.QLineEdit(Form)
        self.id_name.setGeometry(QtCore.QRect(160, 50, 161, 20))
        self.id_name.setClearButtonEnabled(True)
        self.id_name.setObjectName("id_name")
        self.password_name = QtWidgets.QLineEdit(Form)
        self.password_name.setGeometry(QtCore.QRect(160, 80, 161, 20))
        self.password_name.setText("")
        self.password_name.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_name.setReadOnly(False)
        self.password_name.setClearButtonEnabled(True)
        self.password_name.setObjectName("password_name")
        self.password = QtWidgets.QLabel(Form)
        self.password.setGeometry(QtCore.QRect(40, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.update = QtWidgets.QLabel(Form)
        self.update.setGeometry(QtCore.QRect(40, 110, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.update.setFont(font)
        self.update.setText("")
        self.update.setAlignment(QtCore.Qt.AlignCenter)
        self.update.setObjectName("update")
        self.password_2 = QtWidgets.QLabel(Form)
        self.password_2.setGeometry(QtCore.QRect(140, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password_2.setFont(font)
        self.password_2.setAlignment(QtCore.Qt.AlignCenter)
        self.password_2.setObjectName("password_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(150, 150, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login Form"))
        self.id.setText(_translate("Form", "ID  :"))
        self.password.setText(_translate("Form", "Password  :"))
        self.password_2.setText(_translate("Form", "Login"))
        self.pushButton.setText(_translate("Form", "Confirm"))
